default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  port: 5432

development:
  <<: *default
  host: db
  database: app_development

test:
  <<: *default
  host: db
  database: app_test

production:
  <<: *default
  host: database-1.c3cyk6emc6oj.ap-northeast-1.rds.amazonaws.com
  database: app_production
